### ISSUE TITLE
Projects: What to do?

### ISSUE THREAD

**Issue by mr-ubik** [zurutech/gans-from-theory-to-production#12]
Should we try and keep **Projects** organized or should we delete it?

If we decide to keep, we could use it to either track development or showcase a roadmap.

**Comment by galeone** [comment]
Since we are currently upgrading the notebooks to TF2 and we still don't know what the next available features will be, having a proper roadmap is difficult - we only have to stay up-to-date with the tf2 news.

Thus IMHO for now, we can delete the project board and we can start using it again in future when the transition to tf2 is complete.

**Comment by mr-ubik** [comment]
Will do.
